# Generated by Django 4.1.4 on 2023-08-23 16:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djangoApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMatiere', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='djangoApp.matiere')),
                ('intituleProjet', models.CharField(max_length=3000)),
                ('fichierProjet', models.FileField(upload_to='devoirs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), djangoApp.models.validate_file_size])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFiliere', models.CharField(max_length=3000)),
                ('matieres', models.ManyToManyField(to='djangoApp.matiere')),
            ],
        ),
    ]
