# Generated by Django 4.1.4 on 2023-08-24 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_matiere_projet_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_creation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='projet',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
