# Generated by Django 4.1.4 on 2023-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_remove_etudiant_user_user_filire_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
