# Generated by Django 4.1.4 on 2023-08-24 22:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djangoApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_projet_date_creation_projet_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='devoir_soumis',
            field=models.FileField(null=True, upload_to='devoirs_soumis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), djangoApp.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(default=datetime.date.today)),
                ('fichier_soumis', models.FileField(upload_to='devoirs_soumis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), djangoApp.models.validate_file_size])),
                ('commentaires', models.TextField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.etudiant')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.projet')),
            ],
        ),
    ]
