# Generated by Django 4.1.4 on 2023-08-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_alter_user_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_administrateur',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_enseignat',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_etudiant',
            field=models.BooleanField(null=True),
        ),
    ]
