# Generated by Django 4.1.4 on 2023-08-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_projet_devoir_soumis_devoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.etudiant'),
        ),
    ]
