# Generated by Django 4.1.4 on 2023-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_alter_user_is_administrateur_alter_user_is_enseignat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matiere_enseignant',
        ),
        migrations.AddField(
            model_name='user',
            name='matiere_enseignant',
            field=models.ManyToManyField(null=True, to='djangoApp.matiere'),
        ),
    ]
