# Generated by Django 4.1.4 on 2023-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_remove_user_matiere_enseignant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matiere_enseignant',
            field=models.ManyToManyField(to='djangoApp.matiere'),
        ),
    ]
