# Generated by Django 4.1.4 on 2023-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_projet_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='nomEtudiant',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
