# Generated by Django 4.1.4 on 2023-08-25 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0006_etudiant_nometudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
